//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParrentCategoryId { get; set; }
        public Nullable<int> LibraryId { get; set; }
        public long CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<long> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedDataTime { get; set; }
        public bool IsActive { get; set; }
    }
}
