//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string AdditionalName { get; set; }
        public string Description { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> ManufactoryId { get; set; }
        public Nullable<int> MadeInCountryId { get; set; }
        public Nullable<long> ManagedByLibrarianId { get; set; }
        public int LibraryId { get; set; }
        public Nullable<long> ContributorId { get; set; }
        public Nullable<System.DateTime> ContributionDate { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public Nullable<decimal> PresentValue { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public int StatusId { get; set; }
        public long CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<long> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedDataTime { get; set; }
        public bool IsActive { get; set; }
    }
}
